GCC = gcc -ansi -Wpedantic -pedantic-errors -W -Wall -Wextra -Werror -Wfatal-errors  -std=gnu99 -O3

all: exercice_1

exercice_1:
	${GCC} ./exercice_1/server.c -o ./exercice_1/server.out;
	${GCC} ./exercice_1/client.c -o ./exercice_1/client.out;
