GCC = gcc -W -Wall -ansi -std=gnu99 -O3

main: e1

e1:
	${GCC} ./parking_creation.c -o ./parking_creation.out;
	${GCC} ./tickets_distribution.c -o ./tickets_distribution.out;
	${GCC} ./car_output.c -o ./car_output.out;
	${GCC} ./meeting.c -o ./meeting.out;
	${GCC} ./initialize_meeting.c -o ./initialize_meeting.out;
	${GCC} ./e4.c -o ./e4.out;
	${GCC} ./initialize_e4.c -o ./initialize_e4.out;
